model_list:
  - model_name: gpt-4o-mini
    litellm_params:
      model: gpt-4o-mini
      api_base: os.environ/OPENAI_API_BASE
      api_key: "os.environ/OPENAI_API_KEY"

general_settings: 
  master_key: sk-1234 
  database_url: "postgresql://admin:3BhckSAjs6eRmyCwv37ghGepMKuLKuRL@dpg-d18ahhumcj7s73f9gdf0-a.virginia-postgres.render.com/litellmproxy_tr7e"